# Generated by Django 2.1.5 on 2019-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='amendmentFlat1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='amendmentFlat2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='amendmentFlat3',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='commonStockShareOutstanding1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='commonStockShareOutstanding2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='commonStockShareOutstanding3',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='currentFiscalYearEndDate1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='currentFiscalYearEndDate2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='currentFiscalYearEndDate3',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='currentReportingStatus1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='currentReportingStatus2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='currentReportingStatus3',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='documentFiscalPeriodEndDate1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='documentFiscalPeriodEndDate2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='documentFiscalPeriodEndDate3',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='documentFiscalPeriodFocus1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='documentFiscalPeriodFocus2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='documentFiscalPeriodFocus3',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='documentType',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='filerCategory1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='filerCategory2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='filerCategory3',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='seasonedIssuer1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='seasonedIssuer2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='seasonedIssuer3',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='voluntaryFilers1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='voluntaryFilers2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='voluntaryFilers3',
        ),
        migrations.AddField(
            model_name='entity',
            name='row1',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='row2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='row3',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
