# Generated by Django 2.1.5 on 2019-01-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20190128_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='row1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='row2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='row3',
        ),
        migrations.AddField(
            model_name='entity',
            name='payload',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
